ellipse:
  parameters: [0.75, 0.75, 0, -0.75, 0.1, 60, True]   # [a, b, x_center, y_center, Ts, Tm, use angle ref]

rectangle:
  parameters: [1.5, 1.5, 0, 0, 0.1, 60, True]    # [length, width, x_center, y_center, Ts, Tm, use angle ref]

lemniscate:
  parameters: [0.75, 0.8, 0, 0, 0.1, 60, True]    # [a, b, x_center, y_center, Ts, Tm, use angle ref]

sine:
  parameters: [1, 5, 2,0, 0, 0.1, 60, True]    # [A, n,freq, x_center, y_center, Ts, Tm, use angle ref]
  
line:
  parameters: [0, 0, 3, 3, 0.1, 60, True]    # [x_start, y_start, x_end, y_end, Ts, Tm, use angle ref]
  
spiral:
  parameters: [0.4, 0.04, 0, -0.4, 0.1, 60, True]    # [a, b, x_center, y_center, Ts, Tm, use angle ref]
